### ISSUE TITLE
There is no actual compiled version for Chrome.

### ISSUE THREAD

**Issue by Usalabs** [jtyr/protonmail-checker#5]
The extension needs to be compiled as a Chrome extension before being downloaded, because not everyone has Linux that can make use of the 'make' command, and not everyone knows how to compile, so when someone comes here to download and install the Proton Mail extension, they expect it to be a downloadable extension to be directly installed into chrome, with no messing around.

**Comment by jtyr** [comment]
You don't have to compile anything. You can download the extension directly from the Chrome Web Store as indicated in the [README](https://github.com/jtyr/protonmail-checker/blob/master/README.md#usage) file.

**Comment by Usalabs** [comment]
> You don't have to compile anything. You can download the extension directly from the Chrome Web Store as indicated in the [README](https://github.com/jtyr/protonmail-checker/blob/master/README.md#usage) file.

I read the README and the proton mail domain is wrong, they changed their domain a little, it is now mail.proton.me not .com
